services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - user_uploads:/app/uploads
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://api.markus-schwarz.cc
    environment:
      API_URL: https://api.markus-schwarz.cc
    restart: always
    ports:
      - "80:80"

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  user_uploads:
