"""add recipe_comments table

Revision ID: 1face0b29154
Revises: c7e8f9a0b1d2
Create Date: 2026-05-02 15:39:59.509152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1face0b29154'
down_revision: Union[str, Sequence[str], None] = 'c7e8f9a0b1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_comments_id'), 'recipe_comments', ['id'], unique=False)
    op.create_index('ix_recipe_comments_recipe_created', 'recipe_comments', ['recipe_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_recipe_comments_recipe_id'), 'recipe_comments', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_comments_recipe_id'), table_name='recipe_comments')
    op.drop_index('ix_recipe_comments_recipe_created', table_name='recipe_comments')
    op.drop_index(op.f('ix_recipe_comments_id'), table_name='recipe_comments')
    op.drop_table('recipe_comments')
    # ### end Alembic commands ###
