import {
  Apple,
  Baby,
  Beef,
  Beer,
  Bike,
  CalendarDays,
  Car,
  Church,
  CircleAlert,
  CircleParking,
  Clock,
  Coffee,
  CookingPot,
  Cross,
  CupSoda,
  Egg,
  Flame,
  Flower2,
  Footprints,
  HandHeart,
  Heart,
  HardHat,
  House,
  Info,
  Leaf,
  LampFloor,
  Map,
  MapPin,
  Milk,
  Mountain,
  MountainSnow,
  Music,
  PartyPopper,
  Phone,
  Rabbit,
  Salad,
  Sandwich,
  Snowflake,
  Soup,
  Sprout,
  Store,
  Sun,
  Tent,
  Trash2,
  TreePine,
  Trees,
  Truck,
  Users,
  UtensilsCrossed,
  Wheat,
  Wine,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

// Icons, die in den Seiteninhalten (JSON) per Name verwendet werden können.
const ICONS: Record<string, LucideIcon> = {
  apple: Apple,
  baby: Baby,
  beef: Beef,
  beer: Beer,
  bike: Bike,
  calendar: CalendarDays,
  car: Car,
  church: Church,
  alert: CircleAlert,
  parking: CircleParking,
  clock: Clock,
  coffee: Coffee,
  pot: CookingPot,
  cross: Cross,
  juice: CupSoda,
  egg: Egg,
  fire: Flame,
  flower: Flower2,
  hiking: Footprints,
  donate: HandHeart,
  heart: Heart,
  helmet: HardHat,
  house: House,
  info: Info,
  leaf: Leaf,
  lamp: LampFloor,
  map: Map,
  pin: MapPin,
  milk: Milk,
  mountain: Mountain,
  snowmountain: MountainSnow,
  music: Music,
  party: PartyPopper,
  phone: Phone,
  rabbit: Rabbit,
  salad: Salad,
  jause: Sandwich,
  snow: Snowflake,
  soup: Soup,
  sprout: Sprout,
  store: Store,
  sun: Sun,
  tent: Tent,
  trash: Trash2,
  tree: TreePine,
  forest: Trees,
  truck: Truck,
  users: Users,
  food: UtensilsCrossed,
  wheat: Wheat,
  wine: Wine,
}

export default function Icon({ name, className = 'h-6 w-6' }: { name?: string; className?: string }) {
  const Component = (name && ICONS[name]) || Leaf
  return <Component aria-hidden="true" className={className} strokeWidth={1.75} />
}
